---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Aillieo.
--- DateTime: 2018/11/7 18:51
---

RadarImage = class(BaseElement)

function RadarImage:ctor()
    self.elementName = "RadarImage"
end

function RadarImage:Init()

    self.mats = {};
    for i = 1,5 do
        local image = self.objects["Image_" .. i]:GetComponent(typeof(UGUI.Image));
        self.mats[i] = image.material;
    end
    self.valuePairs = {};
    for i = 1,5 do
        self.valuePairs[i] = { self.mats[i], self.mats[i%5 + 1]};
    end
    self.inited = true
end

-- 设置五维属性  index是第几个角1-5  value是值0-1之间
function RadarImage:SetValueForIndex(index,value)
    if not self.inited then
        self:Init();
    end

    local mats = self.valuePairs[index];
    if mats then
        mats[1]:SetFloat("_ValueEnd",value);
        mats[2]:SetFloat("_ValueStart",value);
    end;
end

function RadarImage:SetValues(v1,v2,v3,v4,v5)
    local args = {v1,v2,v3,v4,v5};
    for i = 1,5 do
        self:SetValueForIndex(i,args[i]);
    end
end

return RadarImage